version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: tutorial-Frontend
    restart: unless-stopped
    networks:
      - frontend-backend-network # Can talk to backend
    # depends_on:
    #   - backend

  # Backend service (placeholder for when you creae it)
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #    - "3000:3000"
  #   container_name: tutorial-backend
  #   restart: unless-stopped
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:secret@database:5432/myapp
  #   networks:
  #     - frontend-backend-network # Frontend can call it
  #     - backend-database-network # Can access database
  #   depends_on:
  #    - database

  database:
    image: dhi.io/postgres:18-alpine3.22-dev
    container_name: tutorial-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data  # Persists data
    restart: unless-stopped
    networks:
      - backend-database-network # ONLY backend can access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

# Top-level networks declaration
networks:
  frontend-backend-network:
    driver: bridge
  backend-database-network:
    driver: bridge

# Top-level volumes declaration
volumes:
  db_data: # Named volume (Docker manages storage location)
