package com.example.demo

import com.example.demo.model.User
import com.example.demo.model.CreateUserRequest
import com.example.demo.model.UpdateUserRequest

object UserMapper {

    fun toDto(entity: UserEntity): User {
        return User(
            id = entity.id?.toInt() ?: 0,
            name = entity.name,
            email = entity.email,
            role = User.Role.valueOf(entity.role)
        )
    }

    fun toEntity(dto: CreateUserRequest): UserEntity {
        return UserEntity(
            id = null, // Auto-generated by database
            name = dto.name,
            email = dto.email,
            role = dto.role.value   // Convert Enum to String
        )
    }

    fun updateEntity(entity: UserEntity, dto: UpdateUserRequest): UserEntity {
        return entity.copy(
            name = dto.name ?: entity.name,
            email = dto.email ?: entity.email,
            role = dto.role?.value ?: entity.role
        )
    }
}
